name: Push build to s3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Release Binary to S3
      uses: mostlytyped/s3-put-action@v1.0.0
      with:
        args: --acl-public
      env:
        LOCAL_FILE: dist/MyApp
        REMOTE_FILE: downloads/latest/MyApp
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        INCLUDE_SHA256: true
