name: Push build to s3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build project
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install -g yarn
    - run: npm run build
    
    - name: Release Binary to S3
      uses: mostlytyped/s3-put-action@v1.0.0
      with:
        args: --acl-public
      env:
        LOCAL_FILE: dist/
        REMOTE_FILE: js/dist/
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        INCLUDE_SHA256: true
